apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-sbom-rekor-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/test-sbom-rekor-1:a1084055b390c8b4d950cc293cc53846b892dd27@sha256:55b057dbae1e4de283b3a20bff1e6012e2e96cf17511122c9aa73da62e66a142 # use pre-built to bootstrap 
          name: app-inference
